### ISSUE TITLE
Nest controlled by Jason?

### ISSUE THREAD

**Issue by kevinvla** [jason0x43/alfred-nest#2]
Wanted to try the new beta but should we be worried "Jason"?

![screenshots 2015-07-10 at 8 56 11 pm](https://cloud.githubusercontent.com/assets/3665849/8631529/8e57ecec-2746-11e5-9a31-709531ba0b0f.png)

**Comment by jason0x43** [comment]
That's just how Nest's Oauth set message works. They're basically saying "<company> would like to do the following:", and I'm the company. The authorization only applies to the app, though.
