### ISSUE TITLE
alfred-nest blocked by Gatekeeper

### ISSUE THREAD

**Issue by chrismessina** [jason0x43/alfred-nest#9]
![CleanShot 2020-07-10 at 13 04 37](https://user-images.githubusercontent.com/22610/87193882-eaa47a80-c2ad-11ea-9ee9-303b5c34749e.png)

Not sure if this software is still maintained, but this dialog now pops when trying to activate the Alfred Nest workflow.

**Comment by rbuzatu90** [comment]
This can be easily allowed by opening the extensions folder via 'Open in Finder' and then lunching the app yourself so Mac OS will learn that it's safe.

**Comment by chrismessina** [comment]
Honestly, I think this workflow is just broken. 

alfred-nest is also a binary app — and won't run by itself through Gatekeeper.
